name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  semgrep:
    name: codebase scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: |
          semgrep --config=auto -o semgrep.json .
          wget --post-file=./semgrep.json --header="accept: application/json" --header="Authorization: Token ${{secrets.DEFECT_DOJO_API_KEY}}" --header="Content-Type: multipart/form-data" http://ec2-3-26-221-37.ap-southeast-2.compute.amazonaws.com:8080/api/v2/reimport-scan/
          
  
  trufflehog:
    name: secret scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: scan with trufflehog container
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  publish: 
    needs: semgrep
    name: builds docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build the docker image
        run: docker build . --file dockerimage/Dockerfile --tag my-image-name:$(date +%s)
